#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$APP_BASE_PATH = __DIR__.'/workbench';

$app = require_once __DIR__.'/workbench/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
